# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infra < Formula
  desc "Infra"
  homepage "https://infrahq.com"
  version "0.0.6-test"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://s3.us-east-2.amazonaws.com/releases.infrahq.com/infra/v0.0.6-test/infra_0.0.6-test_darwin_x86_64.zip"
      sha256 "1b379e0cba8f72f082b3c54d41de5928328a59e99450747c4fa2863c2095311a"
    end
    if Hardware::CPU.arm?
      url "https://s3.us-east-2.amazonaws.com/releases.infrahq.com/infra/v0.0.6-test/infra_0.0.6-test_darwin_arm64.zip"
      sha256 "e8a2dc1f2556448ee02f468074055d5d9b69589ae0a96e24e41dcd6c57f3fc58"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://s3.us-east-2.amazonaws.com/releases.infrahq.com/infra/v0.0.6-test/infra_0.0.6-test_linux_x86_64.zip"
      sha256 "ac90cdae40359adfd4d90623b9957d2856b6bd94a5a00c962068487483d94124"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://s3.us-east-2.amazonaws.com/releases.infrahq.com/infra/v0.0.6-test/infra_0.0.6-test_linux_arm64.zip"
      sha256 "6fd3f04ec61bb0179eee323a96748da3a8c14564e3ac9645ca2b7ed8c8b72f0b"
    end
  end

  def install
    bin.install "infra"
  end
end
