# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infra < Formula
  desc "Infra"
  homepage "https://infrahq.com"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_darwin_arm64.zip"
      sha256 "e89c4b661ac753867622b7262a2ffaded5255dfd625edb8cd6b0ac773e87076c"

      def install
        bin.install "infra"
        output = Utils.popen_read("#{bin}/infra completion bash")
        (bash_completion/"infra").write output
        output = Utils.popen_read("#{bin}/infra completion zsh")
        (zsh_completion/"_infra").write output
        output = Utils.popen_read("#{bin}/infra completion fish")
        (fish_completion/"infra.fish").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_darwin_x86_64.zip"
      sha256 "55930c869ffb22b4bf0c36374ab800d895e09973083c6b7c45193712b2be6a76"

      def install
        bin.install "infra"
        output = Utils.popen_read("#{bin}/infra completion bash")
        (bash_completion/"infra").write output
        output = Utils.popen_read("#{bin}/infra completion zsh")
        (zsh_completion/"_infra").write output
        output = Utils.popen_read("#{bin}/infra completion fish")
        (fish_completion/"infra.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_linux_x86_64.zip"
      sha256 "f1cedfdd7c828ad92e171e9a4ec520338ba0deba5cf4f72907b714fe4b70e5b4"

      def install
        bin.install "infra"
        output = Utils.popen_read("#{bin}/infra completion bash")
        (bash_completion/"infra").write output
        output = Utils.popen_read("#{bin}/infra completion zsh")
        (zsh_completion/"_infra").write output
        output = Utils.popen_read("#{bin}/infra completion fish")
        (fish_completion/"infra.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/infrahq/infra/releases/download/v0.21.0/infra_0.21.0_linux_arm64.zip"
      sha256 "140f03fb11e7f28c079410ee01aa4dee05164bfc280c180f837863a94f991a3f"

      def install
        bin.install "infra"
        output = Utils.popen_read("#{bin}/infra completion bash")
        (bash_completion/"infra").write output
        output = Utils.popen_read("#{bin}/infra completion zsh")
        (zsh_completion/"_infra").write output
        output = Utils.popen_read("#{bin}/infra completion fish")
        (fish_completion/"infra.fish").write output
      end
    end
  end
end
