# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infra < Formula
  desc "Infra"
  homepage "https://infrahq.com"
  version "0.13.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.infrahq.com/infra/v0.13.6/infra_0.13.6_darwin_x86_64.zip"
      sha256 "e67d73f19a574cd1a19500b40ac52684397901a52bbcbaf225cd09908612a36b"

      def install
        bin.install "infra"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.infrahq.com/infra/v0.13.6/infra_0.13.6_darwin_arm64.zip"
      sha256 "5f588b99d4d6faab5967872ee1c760f2a9374a468342666f01ea792bfc7cfa6c"

      def install
        bin.install "infra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.infrahq.com/infra/v0.13.6/infra_0.13.6_linux_arm64.zip"
      sha256 "e874ea3037f25917254854ddb48a3b258260de4ba7a95690af3b62a5564c97c8"

      def install
        bin.install "infra"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.infrahq.com/infra/v0.13.6/infra_0.13.6_linux_x86_64.zip"
      sha256 "154b251c9909a6d5accb6ebd8cc16fe19190cccd236864f93b9deb2e851fed41"

      def install
        bin.install "infra"
      end
    end
  end
end
